version: '3'
services:
  kaifusion-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: kaifusion:latest
    container_name: kai-fusion-backend
    ports:
      - "${BACKEND_PORT:-23056}:8000"
    environment:
      # Core Application Settings
      SECRET_KEY: ${SECRET_KEY}
      ENVIRONMENT: ${ENVIRONMENT:-development}
      BACKEND_PORT: ${BACKEND_PORT:-23056}
      BACKEND_DEBUG: ${BACKEND_DEBUG:-true}

      # Database Settings
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL:-false}
      DISABLE_DATABASE: ${DISABLE_DATABASE:-false}
      CREATE_DATABASE: ${CREATE_DATABASE:-true}

      # Database Pool Settings
      DB_POOL_SIZE: ${DB_POOL_SIZE:-30}
      DB_MAX_OVERFLOW: ${DB_MAX_OVERFLOW:-10}
      DB_POOL_TIMEOUT: ${DB_POOL_TIMEOUT:-10}
      DB_POOL_RECYCLE: ${DB_POOL_RECYCLE:-1800}
      DB_POOL_PRE_PING: ${DB_POOL_PRE_PING:-true}

      # Security
      CREDENTIAL_MASTER_KEY: ${CREDENTIAL_MASTER_KEY}

      # Basic Settings
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-*}

      # LangSmith Settings
      LANGCHAIN_TRACING_V2: ${LANGCHAIN_TRACING_V2:-true}
      LANGCHAIN_ENDPOINT: ${LANGCHAIN_ENDPOINT}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      LANGCHAIN_PROJECT: ${LANGCHAIN_PROJECT}

      # Workflow Tracing
      ENABLE_WORKFLOW_TRACING: ${ENABLE_WORKFLOW_TRACING:-true}
      TRACE_AGENT_REASONING: ${TRACE_AGENT_REASONING:-true}
      TRACE_MEMORY_OPERATIONS: ${TRACE_MEMORY_OPERATIONS:-true}

      # JWT Settings
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS:-7}

      # Session Management
      SESSION_TTL_MINUTES: ${SESSION_TTL_MINUTES:-30}
      MAX_SESSIONS: ${MAX_SESSIONS:-1000}

      # File Upload Settings
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      UPLOAD_DIR: ${UPLOAD_DIR:-uploads}

      # Rate Limiting
      RATE_LIMIT_REQUESTS: ${RATE_LIMIT_REQUESTS:-100}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60}

      # Engine Settings
      AF_USE_STUB_ENGINE: ${AF_USE_STUB_ENGINE:-false}

    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    networks:
      - kaifusion-network
    stdin_open: true
    restart: always
    tty: true

networks:
  kaifusion-network:
    driver: bridge